
export const jsSpeakers = [
	{
		name: 'Charlie Gerard',
		title: '#textile-ui #iot #clothing',
	  //title: 'Weaving the web - Programming textile-based interactions in JavaScript',
	  topics: '',
	  image: require('../assets/speakers/charlie_gerard.jpg'),
	},
	{
		name: 'Rubén Sospedra',
		title: '#components #state-machines #UI',
	  //title: 'Mastering UIs with Finite State Machines',
	  topics: '',
	  image: require('../assets/speakers/ruben_sospedra.jpg'),
	},
	{
		name: 'Braden Moore',
		title: '#brainwaves #web-audio-API #healthcare',
	  //title: 'Deciphering Brainwaves with the Web Audio API',
	  topics: '',
	  image: require('../assets/speakers/braden_moore.jpg'),
	},
	{
	  name: 'Mauricio Palma',
		title: '#accessibility #web-apis',
		//title: 'Accessibility vs latest Web APIs. Can’t we just get along?',
	  topics: '',
	  image: require('../assets/speakers/mauricio_palma.jpg')
	},
	{
	  name: 'Isa Silveira',
		title: '#failure #learning #development',
		//title: 'Looking under the rug: the art of learning from failure',
	  topics: '',
	  image: require('../assets/speakers/isa_silveira.jpg'),
	},
	{
	  name: 'Adam Giese',
		title: '#functional-programming #music #web-audio #reactive',
		//title: 'Composing music with composed functions',
	  topics: '',
	  image: require('../assets/speakers/adam_giese.jpg'),
	},
	{
	  name: 'Rebecca Hill',
		//title: 'Essential JavaScript debugging tools for the modern detective',
		title: '#debugging #fixing #node #browser',
	  topics: '',
	  image: require('../assets/speakers/rebecca_hill.jpg'),
	},
	{
	  name: 'Stephanie Nemeth',
		//title: 'How not to read the room: Creating socially awkward wearables with machine learning & javascript',
		title: '#machine-learning #wearables #iot',
	  topics: '',
	  image: require('../assets/speakers/stephanie_nemeth.jpg'),
	},
	{
	  name: 'Eva Ferreira',
		//title: 'Take on me, web browsers!',
		title: '#web-video #effects #videoclips #the-80s #art',
	  topics: '',
	  image: require('../assets/speakers/eva_ferreira.jpg'),
	},
	{
	  name: 'Liran Tal',
		//title: 'StrangerDanger: Finding Security Vulnerabilities Before They Find You!',
		title: '#security #vulnerability #npm',
	  topics: '',
	  image: require('../assets/speakers/liran_tal.jpg'),
	},
	{
	  name: 'Damini Satya Kammakomati',
		//title: 'Taming “Git”osaurus Using Mystical Trees: Understanding complex git trees in the developer fairyland',
		title: '#git #learning #tricks',
	  topics: '',
	  image: require('../assets/speakers/damini_satya.jpg'),
	},
	{
	  name: 'Tejas Kumar',
		//title: 'Legendary Lambdas',
		title: '#serverless #pwa #spa #frameworks',
	  topics: '',
	  image: require('../assets/speakers/tejas_kumar.jpg'),
	},
	{
	  name: 'Shelley Vohr',
		// title: 'API Modernization: Building Bridges As You Cross Them',
		title: '#electron #api #improvement #maintenance',
	  topics: '',
	  image: require('../assets/speakers/shelley_vohr.jpg'),
	},
	{
	  name: 'Vitalii Bobrov',
		// title: 'Algorithms and Their Habitat',
		title: '#computer-science #algorythms #web-apps',
	  topics: '',
	  image: require('../assets/speakers/vitalii_bobrov.jpg'),
	},
	{
	  name: 'Kat Kitay',
		//title: 'Web Norms of the World: An exploration of the internet beyond the West',
		title: '#design #ui #cultural-differences',
	  topics: '',
	  image: require('../assets/speakers/kat_kitay.jpg'),
	},
	{
	  name: 'Benedicte Raae',
		//title: 'A privacy first period tracker? Is it even possible?',
		title: '#privacy #security #web-apps',
	  topics: '',
	  image: require('../assets/speakers/benedicte_raae.jpg'),
	},
	{
	  name: 'Jorge Marin',
		//title: 'Testing in production: Ideas, experiences, limits, roadblocks',
		title: '#testing #production #live-code',
	  topics: '',
	  image: require('../assets/speakers/jorge_marin.jpg'),
	},
	{
	  name: 'Taylor Fairbank',
		//title: 'Javascript Performance in Extreme Conditions: Building WebApps for the Refugee Aid Movement',
		title: '#performance #offline #optimalization',
	  topics: '',
	  image: require('../assets/speakers/taylor_fairbank.jpg'),
	},
	{
	  name: 'Balázs Korossy-Khayll',
		//title: 'Testing presentation components visually',
		title: '#visual #testing #storybook',
	  topics: '',
	  image: require('../assets/speakers/balazs_korossy_khayll.jpg'),
	}
  ]
  
export const cssSpeakers = [
	{
	  name: 'David Khourshid',
		//title: 'Crafting Stateful Styles with State Machines',
		title: '#stateful #styles #state-machines',
	  topics: '',
	  image: require('../assets/speakers/david_khourshid.jpg'),
	},
	{
	  name: 'Jeremy Wagner',
		//title: 'The Weird (yet Practical) World of CSS Paint Worklets',
		title: '#houdini #worklets #js-in-css',
	  topics: '',
	  image: require('../assets/speakers/jeremy_wagner.jpg'),
	},
	{
	  name: 'Giulia Cardieri',
		// title: 'CSS Games and Drawings in the real world: useful or just fun?',
		title: '#games #drawing #learning',
	  topics: '',
	  image: require('../assets/speakers/giulia_cardieri.jpg'),
	},
	{
	  name: 'Damien Senger',
		//title: 'Variable fonts & readability: the rising of custom reading experiences',
		title: '#variable-fonts #typography',
	  topics: '',
	  image: require('../assets/speakers/damien_senger.jpg'),
	},
	{
	  name: 'Yu Ling Cheng',
		// title: 'Building better products faster: DevUx is the new DevOps',
		title: '#developer-experience #communication #teamwork',
	  topics: '',
	  image: require('../assets/speakers/yu_ling_cheng.jpg'),
	},
	{
	  name: 'Mike Riethmuller',
		// title: 'CSS Architecture for Modern Web Applications',
		title: '#architecture #design-systems #components',
	  topics: '',
	  image: require('../assets/speakers/mike_riethmuller.jpg'),
	},
	{
	  name: 'Xavier Cazalot',
		//title: 'The Path to SVG Animations',
		title: '#svg #animations',
	  topics: '',
	  image: require('../assets/speakers/xavier_cazalot.jpg'),
	},
	{
	  name: 'Kathrin Holzmann',
		//title: 'CSS in JS - beware the Hype!',
		title: '#architecture #components #css-in-js',
	  topics: '',
	  image: require('../assets/speakers/kathrin_holzmann.jpg'),
	},
	{
	  name: 'Alan Stearns',
		//title: 'Getting Browser Bugs Fixed',
		title: '#browsers #vendors #bugs',
	  topics: '',
	  image: require('../assets/speakers/alan_stearns.jpg'),
	},
  ]